from echo_agent.cli.renderer_base import RenderSink


class _Complete:
    def on_turn_accepted(self, event_id): ...
    def on_user_reply_token(self, inbound_id, text): ...
    def on_user_reply_reset(self, inbound_id): ...
    def on_user_reply_final(self, inbound_id, text): ...
    def on_cognitive(self, ev): ...
    def on_error(self, msg): ...
    def notify_disconnected(self): ...
    def notify_reconnected(self): ...
    def replay_missed_reply(self, text, event_id=""): ...


class _MissingOne:
    def on_turn_accepted(self, event_id): ...
    def on_user_reply_token(self, inbound_id, text): ...
    def on_user_reply_reset(self, inbound_id): ...
    def on_user_reply_final(self, inbound_id, text): ...
    def on_cognitive(self, ev): ...
    def on_error(self, msg): ...
    def notify_disconnected(self): ...
    def notify_reconnected(self): ...
    # replay_missed_reply missing


def test_complete_implementation_satisfies_protocol():
    assert isinstance(_Complete(), RenderSink)


def test_missing_method_fails_protocol():
    assert not isinstance(_MissingOne(), RenderSink)


def test_existing_tui_app_satisfies_protocol():
    # The Textual app is the reference implementation; if it drifts out of the
    # contract, the inline renderer and the bridge disagree about the sink.
    from echo_agent.cli.tui.app import EchoTUI
    for name in (
        "on_turn_accepted", "on_user_reply_token", "on_user_reply_reset",
        "on_user_reply_final", "on_cognitive", "on_error",
        "notify_disconnected", "notify_reconnected", "replay_missed_reply",
    ):
        assert callable(getattr(EchoTUI, name, None)), f"EchoTUI lacks {name}"
